### ISSUE TITLE
40 second countdown for reinficrnements on every wave start

### ISSUE THREAD

**Issue by Minotaur830** [LlemonDuck/fortis-colosseum#12]
Hey man could you please add a simple 40 second countdown that starts every wave? It would be really simple and help a lot with reinficrnements. Its always just 40 seconds so I imagine it would be easy to implement.

**Comment by LlemonDuck** [comment]
I'm not interested in adding this explicitly, but you can get the same info by enabling splits and watching the in-wave timer count to 40:00. You can reduce spam by limiting the display to a single wave.

I believe adding a countdown or something more specifically about spawn timing would violate some rules on indicating timing of mechanics.
