### ISSUE TITLE
Add a Censor option to the Wave 12 loot

### ISSUE THREAD

**Issue by Processhf** [LlemonDuck/fortis-colosseum#4]
This is a suggestion on a new feature because I'm too stupid to code it myself 😅

A lot of people on Reddit have asked for a feature like this; the idea is that you can censor the loot you would get for Wave 12 to prevent players from getting nervous due to seeing a unique or pet in the Wave 12 loot box.

It could be a straight up censor to all the loot, or just censoring the loot other than the Quiver, the concept remains the same.

Hopefully you'll consider adding this!

**Comment by LlemonDuck** [comment]
Sounds like a great idea! I'll pick this up soon

**Comment by LlemonDuck** [comment]
https://github.com/LlemonDuck/fortis-colosseum/assets/1868974/2a786fca-59a0-4cd2-a453-8d35589a2812

Done in 1928995652f13f7155a45f9527b2fcdf112922a5
