### ISSUE TITLE
Add an option to show only current wave in wave splits

### ISSUE THREAD

**Issue by Jdifo** [LlemonDuck/fortis-colosseum#6]
Showing wave splits is very useful for knowing when the reinforcements spawn but it also covers up a significant portion of the screen by the later waves. Having a small box with just the current wave number and duration would be really useful.

**Comment by LlemonDuck** [comment]
I'll do you one better: you can now render any number of recent waves you choose:
![image](https://github.com/LlemonDuck/fortis-colosseum/assets/1868974/f794b122-ceca-405c-a88b-44405a8f75a2)
![image](https://github.com/LlemonDuck/fortis-colosseum/assets/1868974/b3dce679-8eea-4168-83c2-8cf04f4171d9)
![image](https://github.com/LlemonDuck/fortis-colosseum/assets/1868974/7b347cc3-91ad-40e7-b843-c0b54e91f9f8)

Completed in 5b520e93231fa18814dab3f7bed99482297128b5
